# List of VMs to be managed by Vagrant
mynodes = {
  "node1" => { "ip" => "10.1.1.11" },
  "node2" => { "ip" => "10.1.1.12" }
}

###############################################################################
#
# Do not make any changes below this line
#
###############################################################################

#
# Extract all node names
#
mynodenames = mynodes.keys

#
# Configure all VMs
#
Vagrant.configure("2") do |config|

  # Pin CentOS 8 version 1905.1 as OS
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"

  # VirtualBox settings for all VMs
  config.vm.provider :virtualbox do |vb|
    # Add all cluster nodes to the same VirtualBox group
    vb.customize ["modifyvm", :id, "--groups", "/mylab"]
  end  # Loop |vb|

  # Iterate over all nodes nodenames
  mynodenames.each do |node|

    # Define VM
    config.vm.define node do |current_node|

      # Set hostname in guest OS
      current_node.vm.hostname = node

      # Set IP address on shared cluster network
      current_node.vm.network "private_network", ip: mynodes[node]["ip"],
        virtualbox__intnet: "mylab"

      # Virtualbox settings for current VM
      current_node.vm.provider :virtualbox do |vb|
        # Set VM name in VirtualBox
       vb.name = node
     end  # Loop |vb|

    end  # Loop |current_node|
  end  # Loop |node|

end  # Loop |config|
